# Generated by Django 3.1 on 2020-08-31 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200831_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Momo',
            new_name='About',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'About me', 'verbose_name_plural': 'About me'},
        ),
    ]
